name: Create Release and publish packages

on:
  push:
    tags:
    # Tags in the form, es-ES-vmajor.minor.patch
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade -r requirements/release.txt
    - name: Prepare env variables
      run: |
        export CURRENT_TAG=`python .github/scripts/parse_ref.py`
        echo ::set-env name=CURRENT_TAG::$CURRENT_TAG
        export CURRENT_LOCALE_DIR=`python .github/scripts/parse_release.py`
        echo ::set-env name=CURRENT_LOCALE_DIR::$CURRENT_LOCALE_DIR
    - name: Build release artefacts
      run: |
        cd $CURRENT_LOCALE_DIR
        check-manifest -v
        python setup.py sdist bdist_wheel
        python -m twine check dist/*
        ls
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.CURRENT_TAG }}
        name: Release ${{ env.CURRENT_TAG }}
        artifacts: ${{ env.CURRENT_LOCALE_DIR }}/dist/*
        body: Release ${{ env.CURRENT_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish PyPI Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        cd $CURRENT_LOCALE_DIR
        python -m twine upload dist/*
        ls
